# Generated by Django 6.0 on 2025-12-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cetagory_customer_user_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_user',
            name='image',
            field=models.ImageField(default='default_png', null=True, upload_to='image/'),
        ),
    ]
