# Generated by Django 6.0 on 2025-12-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customer_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='brands/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cetagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cetagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dicount',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_user',
            name='image',
            field=models.ImageField(blank=True, default='default_png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_png', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
    ]
